### ISSUE TITLE
ТестТес

### ISSUE THREAD

**Issue by Lnikolaeva** [RakhimyanTim/partnerum.github.io#1]
Надо будет тестить и записывать задачки (если будут)
[app-release.apk.zip](https://github.com/RakhimyanTim/partnerum.github.io/files/3794614/app-release.apk.zip)

**Comment by Lnikolaeva** [comment]
Тест 3

**Comment by RakhimyanTim** [comment]
Вот другая сборка 
[app-release.apk.zip](https://github.com/RakhimyanTim/partnerum.github.io/files/3797981/app-release.apk.zip)

**Comment by RakhimyanTim** [comment]
3-я сборка 
[app-release.apk.zip](https://github.com/RakhimyanTim/partnerum.github.io/files/3799282/app-release.apk.zip)

**Comment by RakhimyanTim** [comment]
После часового общения по скайпу разбили на задачи.
